export const projects = [
  {
    title: 'Valor Enterprises - Internal',
    description: "Utilizing React, Node.js, Express, Material UI, TailwindCSS, AWS, this application is the foundation and works of this real estate company. Although it is only available to its employees, this has a ton of features from displaying properties on a map, changing data on the fly, employee training portal, and many more for the company to operate.",
      image: '/valor.png',
      tags: ['React', 'Express', 'AWS DynamoDB', 'AWS Cognito', 'AWS Amplify', 'AWS S3', 'AWS Route53/Cloudfront'],
    source: 'https://valorenterprises.netlify.app/',
    visit: 'https://github.com/gioadorno/Valor-Enterprises',
    id: 0,
  },
  {
    title: 'Shoppy',
    description:"I have created this site to showcase how a modern and user-friendly a dashboard is built. Easy-to-use features such as light/dark mode, theme colors, and showcasing different demo charts/graphs.",
    image: '/shoppy.png',
    tags: ['React', 'JavaScript', 'TailwindCSS', 'Syncfusion'],
    source: 'https://theshoppy.netlify.app/',
    visit: 'https://github.com/gioadorno/Shoppy',
    id: 1,
  },
  {
    title: 'KeygleeDispo',
    description: "One of my earlier builds for the KeygleeDispo/ValorHomes company. Utilizing both an internal and customer-facing system I have built, this allows customers to view and purchase properties by creating an account, while the company is able to utilizing the internal system by logging in and creating/submitting tasks in their own dashboard.",
    image: '/keyglee.png',
    tags: ['React', 'MongoDB', 'Express', 'NodeJS', 'Redux', 'Materiaul UI'],
    source: 'https://yourvalorhomes.netlify.app',
    visit: '',
    id: 2,
  },
  {
    title: 'TheStay',
    description: "I've built this project to showcase more on the design aspect with some functionality. In the search bar the user is able to type in a destination, select the date range, and number of guests to see where'd they like to stay for that duration. It will then populate pre-made information to the user for the date and location. Go check it out!",
    image: '/thestay.png',
    tags: ['NextJS', 'TailwindCSS', 'Calendar-Picker', 'Mapbox'],
    source: 'https://the-stay.vercel.app/',
    visit: 'https://github.com/gioadorno/TheStay',
    id: 3,
  },
  {
    title: 'CoreX Studios',
    description: "Utilizing the public movie database, this automated application is pulling the most recent/popular tv shows and movies to the user. The information provided gives a brief description as well as the amount of thumbs up users rate that particular movie. Users can select categories as well as 'Trending' or 'Top Rated' movies/shows.",
    image: '/corex.png',
    tags: ['NextJS', 'TailwindCSS'],
    source: 'https://corexstudios.netlify.app/',
    visit: '',
    id: 4,
  },
  {
    title: 'Coach App',
    description: "I unfortunately cannot go into too much detail with this particular app, but this is a mockup I have made for an NBA team. This allows the coach, while mid-game, to easily enter up to five players and track times, as well as display other useful information. This is not the final version.",
    image: '/coach.png',
    tags: ['NextJS', 'TailwindCSS'],
    source: 'https://coach-app-two.vercel.app/',
    visit: 'https://github.com/gioadorno/coach-app',
    id: 5,
  },
  {
    title: 'Portfolio - Version 1',
    description: "This was one of my very first builds as a developer, showcasing my first portfolio.",
    image: '/port1.png',
    tags: ['ReactJS', 'Styled Components', 'Express/Node', 'MongoDB/Mongoose', 'Redux'],
    source: 'https://gioportfolio1.netlify.app/',
    visit: 'https://github.com/gioadorno/Portfolio',
    id: 6,
  },
    {
    title: 'Portfolio - Version 2',
    description: "Second version of my portfolio site",
    image: '/port2.png',
    tags: ['ReactJS, Styled Components'],
    source: 'https://giovanni-resume.netlify.app',
    visit: '',
    id: 7,
  },
  {
    title: 'The Blog',
    description: "Simple, easy-to-use blog website, allowing users to like and comment on the blog-owner's post.",
    image: '/theblog.png',
    tags: ['NextJS', 'Typescript', 'GROQ', 'SanityIO', 'TailwindCSS'],
    source: 'https://theblog-omega.vercel.app/',
    visit: 'https://github.com/gioadorno/theblog',
    id: 8,
  },
];

export const TimeLineData = [
  { year: 2008, text: 'Utilizing 3D Animation and Modeling to create 3D envrionments', },
  { year: 2012, text: 'Went to college for Audio Engineering', },
  { year: 2013, text: 'Competed in local Mens Physique Show', },
  { year: 2015, text: 'Where my software journey began', },
  { year: 2016, text: 'Owning a couple of businesses, utilized my skills to build my own sites at the time', },
  { year: 2021, text: 'Decided to go back to software full time and master my skills', },
];